---
name: CI
on:
  - push

permissions: {}

jobs:
  lint:
    name: Lint source-code using hlint
    runs-on: ubuntu-22.04
    steps:
      - name: Install hlint
        uses: haskell/actions/hlint-setup@v2.2.0
        with:
          version: 3.5
      - name: Checkout source-code
        uses: actions/checkout@v3.3.0
      - name: Run hlint
        uses: haskell/actions/hlint-run@v2.2.0
        with:
          fail-on: status
