---
name: CI
on:
  - pull_request

permissions: {}

jobs:
  lint:
    name: Lint source-code using hlint
    runs-on: ubuntu-22.04
    steps:
      - name: Install hlint
        uses: haskell/actions/hlint-setup@v2.2.0
        with:
          version: 3.5
      - name: Checkout source-code
        uses: actions/checkout@v3.3.0
      - name: Run hlint
        uses: haskell/actions/hlint-run@v2.2.0
        with:
          fail-on: status

  build-and-test:
    name: Build and test packages
    strategy:
      matrix:
        ghc: ['8.10.7', '9.0.2', '9.2.4', '9.4.2']
    runs-on: ubuntu-22.04
    steps:
      - name: Install GHC
        uses: haskell/actions/setup@v2.2.0
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: 3.8.1.0
      - name: Checkout source-code
        uses: actions/checkout@v3.3.0
      - name: Build dependencies
        run: |
          cabal build --dependencies-only all
      - name: Build
        run: |
          cabal build all
      - name: Build test dependencies
        run: |
          cabal build --enable-tests --dependencies-only all
      - name: Build tests
        run: |
          cabal build --enable-tests all
      - name: Run tests
        run: |
          cabal test --test-show-details=direct
