---
name: UML
on:
  - push
  - pull_request

jobs:
  build-uml:
    name: Build UML
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        linux:
          - 5.13
          - 5.19

    env:
      ARCH: um
      SUBARCH: x86_64

    steps:
      - name: Download and unpack Linux kernel sources
        run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-${{ matrix.linux }}.tar.xz
          tar xf linux-${{ matrix.linux }}.tar.xz
      - name: Patch Linux kernel sources
        working-directory: linux-${{ matrix.linux }}
        run: |
          sed -i '/ARCH_EPHEMERAL_INODES/d' arch/um/Kconfig
      - name: Configure Linux kernel
        working-directory: linux-${{ matrix.linux }}
        run: |
          make tinyconfig
          echo "CONFIG_UID16=y" >> .config
          echo "CONFIG_MULTIUSER=y" >> .config
          echo "CONFIG_KERNFS=y" >> .config
          echo "CONFIG_SYSFS=y" >> .config
          echo "CONFIG_SECURITY=y" >> .config
          echo "CONFIG_SECURITY_PATH=y" >> .config
          echo "CONFIG_SECURITY_LANDLOCK=y" >> .config
          make olddefconfig
      - name: Build Linux kernel
        working-directory: linux-${{ matrix.linux }}
        run: |
          make -j2 linux
